<div id="stopka">

<div id="menu">
<ul id="navlist">
<li><a href ="se.html">Secret Energy</a></li>
<li><a href ="exd.html">Extreme Discotheque</a></li>
</ul>
</div>

<div id="stopka2">&copy;Mikey 2008-2009<script language="JavaScript"> 
document.write('<a class="mail" href="mailto:info@');
document.write('dwienuty.pl">');document.write('info@');
document.write('dwienuty.pl</a>'); 
</script>


</div>

</div><!-- koniec stopka -->
</body>
</html>