<?xml version="1.0" encoding="iso-8859-2"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
  <meta http-equiv="Content-type" content="application/xhtml+xml; charset=iso-8859-2" />
  <meta name="Description" content=" Oficjalna witryna projektu psychedelic trance-Extreme Discotheque oraz projektu elektro Secret Energy." />
  <meta name="Keywords" content=" psychedelic,trance,electronic,music,House,Tech-House,Techno,Progressive,muzyka,elektroniczna, Mikey, Extreme, Discotheque, Secret, Energy, Michał, Ziółek " />
  <meta name="robots" content=" index, follow " />
	<meta name="Mikey" content=" Michal Ziolek " />
  <meta name="Generator" content="kED" />
  <title> Dwie nuty - Psytrance i Elektronika</title>
  <link rel="Stylesheet" href="style.css" type="text/css" />
</head>
<body>

<div id="topcalosc"><!-- top -->

<div id="top"><a href="index.html"><img class="topimg" src="grafika/logotop.jpg" /></a></div>

<div id="topmirror"></div>

<div id="menu">
<ul id="navlist">
<li><a href ="linki.html">Linki</a></li>
<li><a href ="download.html">Download</a></li>
<li><a href ="imprezy.html">Imprezy</a></li>
<li><a href ="biografia.html">Kim jestem</a></li>
<li><a href ="news.html">News</a></li>
<li><a href ="wstep.html">Wstęp</a></li>
</ul>
</div>

</div><!-- koniec top -->
